networks:
  default:
    driver: bridge

services:
  web:
    build:
      context: ./nginx
    image: nginx:alpine
    networks:
      - default
    volumes:
      - import-service:/var/www/html
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: import_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - default
    volumes:
      - db-data:/var/lib/mysql

  php:
    build:
      context: ./php
    image: php:8.3-fpm
    networks:
      - default
    volumes:
      - import-service:/var/www/html

  php-cli:
    image: php:8.3-cli
    networks:
      - default
    volumes:
      - import-service:/var/www/html
    working_dir: /var/www/html

  redis:
    image: redis:alpine
    networks:
      - default

volumes:
  db-data:
  import-service:
    driver: local
    driver_opts:
      type: none
      device: ${IMPORT_SERVICE_PATH}
      o: bind
